import { Calendar, Trophy, BrushCleaning, Handshake, Rss, Newspaper } from "lucide-react";

import AnnounceImage1 from "../assets/AnnounceImage1.jpg" 
import AnnounceImage2 from "../assets/AnnounceImage2.jpg"
import AnnounceImage3 from "../assets/AnnounceImage3.jpg"
import AnnounceImage4 from "../assets/AnnounceImage4.jpg"
import AnnounceImage5 from "../assets/AnnounceImage5.jpg"
import AnnounceImage6 from "../assets/AnnounceImage6.jpg"
import AnnounceImage7 from "../assets/AnnounceImage7.jpg"

const commonParag = "Lorem ipsum dolor sit amet consectetur adipiscing elit. Pretium tellus duis convallis tempus leo eu aenean. Iaculis massa nisl malesuada lacinia integer nunc posuere. Conubia nostra inceptos himenaeos orci varius natoque penatibus. Nulla molestie mattis scelerisque maximus eget fermentum odio. Blandit quis suspendisse aliquet nisi sodales consequat magna. Ligula congue sollicitudin erat viverra ac tincidunt nam. Velit aliquam imperdiet mollis nullam volutpat porttitor ullamcorper. Dui felis venenatis ultrices proin libero feugiat tristique. Cubilia curae hac habitasse platea dictumst lorem ipsum. Sem placerat in id cursus mi pretium tellus. Fringilla lacus nec metus bibendum egestas iaculis massa. Taciti sociosqu ad litora torquent per conubia nostra. Ridiculus mus donec rhoncus eros lobortis nulla molestie. Mauris pharetra vestibulum fusce dictum risus blandit quis. Finibus facilisis dapibus etiam interdum tortor ligula congue. Justo lectus commodo augue arcu dignissim velit aliquam. Primis vulputate ornare sagittis vehicula praesent dui felis. Senectus netus suscipit auctor curabitur facilisi cubilia curae. Quisque faucibus ex sapien vitae pellentesque sem placerat.";

export const Data = [
  {
    id: 1029384756,
    Icon: <Calendar />,
    image: AnnounceImage1,
    label: "Event",
    date: "March 15, 2026",
    bgColor: "bg-blue-500",
    labelColor: "bg-blue-500/10",
    labelTextColor: "text-blue-500",
    title: "Blockchain Security",
    desc: "Immutable records and tamper-proof documentation for your intellectual property assets using distributed ledger technology.",
    parag: commonParag,
    parag1: commonParag,
    parag2: commonParag,
    parag3: commonParag,
  },
  {
    id: 2193847560,
    Icon: <Trophy />,
    image: AnnounceImage2,
    label: "Achievement",
    date: "February 10, 2026",
    bgColor: "bg-emerald-500",
    labelColor: "bg-emerald-500/10",
    labelTextColor: "text-emerald-500",
    title: "AI-Powered Analysis",
    desc: "Advanced machine learning algorithms to analyze, categorize, and monitor your IP portfolio for potential infringements.",
    parag: commonParag,
    parag1: commonParag,
    parag2: commonParag,
    parag3: commonParag,
  },
  {
    id: 3847561029,
    Icon: <BrushCleaning />,
    image: AnnounceImage3,
    label: "Maintenance",
    date: "February 01, 2026",
    bgColor: "bg-amber-500",
    labelColor: "bg-amber-500/10",
    labelTextColor: "text-amber-500",
    title: "Cloud Infrastructure",
    desc: "Secure, scalable cloud-based platform ensuring your data is accessible anywhere while maintaining enterprise-grade security.",
    parag: commonParag,
    parag1: commonParag,
    parag2: commonParag,
    parag3: commonParag,
  },
  {
    id: 4756102938,
    Icon: <Handshake />,
    image: AnnounceImage4,
    label: "Partnership",
    date: "January 20, 2026",
    bgColor: "bg-indigo-500",
    labelColor: "bg-indigo-500/10",
    labelTextColor: "text-indigo-500",
    title: "Secure Data Storage",
    desc: "End-to-end encrypted storage solutions with redundant backups and compliance with international data protection standards.",
    parag: commonParag,
    parag1: commonParag,
    parag2: commonParag,
    parag3: commonParag,
  },
  {
    id: 5610293847,
    Icon: <Rss />,
    image: AnnounceImage5,
    label: "Update",
    date: "January 05, 2026",
    bgColor: "bg-cyan-500",
    labelColor: "bg-cyan-500/10",
    labelTextColor: "text-cyan-500",
    title: "Real-Time Monitoring",
    desc: "Continuous monitoring of your IP assets with instant alerts for potential violations or unauthorized usage worldwide.",
    parag: commonParag,
    parag1: commonParag,
    parag2: commonParag,
    parag3: commonParag,
  },
  {
    id: 6102938475,
    Icon: <Newspaper />,
    image: AnnounceImage6,
    label: "News",
    date: "December 15, 2025",
    bgColor: "bg-slate-500",
    labelColor: "bg-slate-500/10",
    labelTextColor: "text-slate-500",
    title: "API Integration",
    desc: "Seamless integration with existing systems through our robust API, enabling automated workflows and data synchronization.",
    parag: commonParag,
    parag1: commonParag,
    parag2: commonParag,
    parag3: commonParag,
  },
  {
    id: 7102938476,
    Icon: <Newspaper />,
    image: AnnounceImage7,
    label: "News",
    date: "December 01, 2025",
    bgColor: "bg-slate-500",
    labelColor: "bg-slate-500/10",
    labelTextColor: "text-slate-500",
    title: "Smart Contract Automation",
    desc: "Self-executing digital agreements that streamline licensing royalties and automate ownership transfers without intermediaries.",
    parag: commonParag,
    parag1: commonParag,
    parag2: commonParag,
    parag3: commonParag,
  },
  {
    id: 8102938477,
    Icon: <Handshake />,
    image: AnnounceImage1,
    label: "Partnership",
    date: "November 18, 2025",
    bgColor: "bg-indigo-500",
    labelColor: "bg-indigo-500/10",
    labelTextColor: "text-indigo-500",
    title: "Biometric Authentication",
    desc: "Multi-factor security layers including facial and fingerprint recognition to ensure only authorized personnel access sensitive IP.",
    parag: commonParag,
    parag1: commonParag,
    parag2: commonParag,
    parag3: commonParag,
  },
  {
    id: 9102938478,
    Icon: <BrushCleaning />,
    image: AnnounceImage2,
    label: "Maintenance",
    date: "November 05, 2025",
    bgColor: "bg-amber-500",
    labelColor: "bg-amber-500/10",
    labelTextColor: "text-amber-500",
    title: "Global Compliance Tracking",
    desc: "Automated updates on international patent laws and regulatory changes to keep your portfolio compliant across all jurisdictions.",
    parag: commonParag,
    parag1: commonParag,
    parag2: commonParag,
    parag3: commonParag,
  },
  {
    id: 1102938479,
    Icon: <Calendar />,
    image: AnnounceImage3,
    label: "Event",
    date: "October 22, 2025",
    bgColor: "bg-blue-500",
    labelColor: "bg-blue-500/10",
    labelTextColor: "text-blue-500",
    title: "Predictive Analytics",
    desc: "Forecasting market trends and potential IP valuation shifts using historical data and competitive landscape modeling.",
    parag: commonParag,
    parag1: commonParag,
    parag2: commonParag,
    parag3: commonParag,
  },
  {
    id: 1210293848,
    Icon: <Calendar />,
    image: AnnounceImage4,
    label: "Event",
    date: "October 10, 2025",
    bgColor: "bg-blue-500",
    labelColor: "bg-blue-500/10",
    labelTextColor: "text-blue-500",
    title: "Quantum-Resistant Encryption",
    desc: "Future-proofing your data security with advanced cryptographic protocols designed to withstand next-generation computing threats.",
    parag: commonParag,
    parag1: commonParag,
    parag2: commonParag,
    parag3: commonParag,
  },
  {
    id: 1310293849,
    Icon: <BrushCleaning />,
    image: AnnounceImage5,
    label: "Maintenance",
    date: "September 28, 2025",
    bgColor: "bg-amber-500",
    labelColor: "bg-amber-500/10",
    labelTextColor: "text-amber-500",
    title: "Collaborative Workspaces",
    desc: "Centralized environments for legal teams and creators to review, annotate, and co-author IP documentation in real-time.",
    parag: commonParag,
    parag1: commonParag,
    parag2: commonParag,
    parag3: commonParag,
  },
];